#! /usr/local/bin/bash

# Launchctl on Macintosh development systems runs this every morning, half an hour after
# ingest_requirement_blocks is run.

rsync -vte ssh 149.4.44.244:/Users/vickery/Projects/ingest_requirement_blocks/latest_queries/* \
                            ./latest_queries

mv latest_queries/* archives/
./ingest_requirement_blocks.py
(
  cd ~/Projects/dgw_processor
  ./parse_active.py -c
  ./parse_active.py -tl 3600
)
