#! /usr/local/bin/bash


rsync -vte ssh 149.4.44.244:/Users/vickery/Projects/ingest_requirement_blocks/latest_queries/* \
                            ./latest_queries

mv latest_queries/* archives/
./ingest_requirement_blocks.py
(
  cd ~/Projects/dgw_processor
  ./parse_active.py -c
  ./parse_active.py -tl 3600
)
