#! /usr/local/bin/bash

# Run this after getting updated query files from Lehman
[[ `hostname` = lehman ]] && return

# Move most recent from downloads to latest, and process them
./ingest_requirement_blocks.py

# Update parsing
(
  cd ~/Projects/dgw_processor
  ./parse_active.py -c
  ./parse_active.py -tl 3600
)
